import React, { useState, useEffect } from 'react';
import Card from '../../components/ui/Card';
import Badge from '../../components/ui/Badge';
import Button from '../../components/ui/Button';
import Select from '../../components/ui/Select';
import Table from '../../components/ui/Table';
import { 
  FileText, Download, Printer, RefreshCw, AlertCircle, FileOutput, CheckCircle, Search, Calendar, MapPin
} from 'lucide-react';
import { 
  mockReportsHistory, reportTypes, dateRangeOptions, getMockReportPreviewData 
} from '../../data/mockReports';
import { villagesList } from '../../data/mockUsers';
import { districtsList } from '../../data/mockAnalytics';
import { operatorsList } from '../../data/mockVillages';

const Reports = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Filters for generating a report
  const [selectedReportType, setSelectedReportType] = useState(reportTypes[0]);
  const [dateRange, setDateRange] = useState(dateRangeOptions[1]);
  const [villageFilter, setVillageFilter] = useState('');
  const [districtFilter, setDistrictFilter] = useState('');
  const [operatorFilter, setOperatorFilter] = useState('');
  
  // Preview State
  const [previewData, setPreviewData] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    const fetchHistory = async () => {
      try {
        setLoading(true);
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 600));
        setHistory(mockReportsHistory);
        setError(null);
      } catch (err) {
        setError('Failed to fetch reports history.');
      } finally {
        setLoading(false);
      }
    };
    fetchHistory();
  }, []);

  const handleClearFilters = () => {
    setSelectedReportType(reportTypes[0]);
    setDateRange(dateRangeOptions[1]);
    setVillageFilter('');
    setDistrictFilter('');
    setOperatorFilter('');
    setPreviewData(null);
  };

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setPreviewData(null);
    
    // Simulate generation time
    setTimeout(() => {
      const data = getMockReportPreviewData(selectedReportType, villageFilter || 'All Villages', dateRange);
      setPreviewData(data);
      setIsGenerating(false);
      
      // Optionally add to history
      const newHistoryRecord = {
        id: `RPT-00${history.length + 1}`,
        reportType: selectedReportType,
        generatedDate: new Date().toISOString(),
        generatedBy: 'Admin User',
        dateRange: dateRange,
        village: villageFilter || 'All Villages',
        district: districtFilter || 'All Districts',
        status: 'Completed'
      };
      setHistory([newHistoryRecord, ...history]);
    }, 1000);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCSV = () => {
    if (!previewData || !previewData.data) return;
    
    const headers = previewData.columns.join(',');
    const rows = previewData.data.map(obj => Object.values(obj).map(v => `"${v}"`).join(',')).join('\n');
    const csvContent = `data:text/csv;charset=utf-8,${headers}\n${rows}`;
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `${selectedReportType.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const getStatusBadgeVariant = (status) => {
    switch (status) {
      case 'Completed': return 'success';
      case 'Failed': return 'danger';
      case 'Processing': return 'warning';
      default: return 'default';
    }
  };

  const historyColumns = [
    { header: 'Report ID', accessor: 'id' },
    { header: 'Type', accessor: 'reportType' },
    { header: 'Date Generated', render: (row) => new Date(row.generatedDate).toLocaleString() },
    { header: 'Generated By', accessor: 'generatedBy' },
    { header: 'Date Range', accessor: 'dateRange' },
    { header: 'Village Scope', accessor: 'village' },
    { 
      header: 'Status', 
      render: (row) => (
        <Badge variant={getStatusBadgeVariant(row.status)}>
          {row.status}
        </Badge>
      )
    },
    {
      header: 'Actions',
      render: (row) => (
        <div className="flex items-center gap-3">
          <button 
            className="text-gov-blue hover:underline text-sm font-medium"
            onClick={() => {
              setSelectedReportType(row.reportType);
              setDateRange(row.dateRange);
              setVillageFilter(row.village !== 'All Villages' ? row.village : '');
              handleGenerateReport();
            }}
          >
            View / Re-run
          </button>
        </div>
      )
    }
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gov-blue"></div>
        <span className="ml-2 text-gray-600">Loading reports module...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6 pb-10">
      {/* Non-printable Header */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4 print:hidden">
        <div>
          <h2 className="text-2xl font-bold text-gray-800">Reports & Documents</h2>
          <p className="text-gray-500 text-sm mt-1">Generate operational reports for monitoring water supply, service quality, complaints, maintenance and fee collection across villages.</p>
        </div>
      </div>

      {/* Report Configuration Panel */}
      <Card className="p-5 print:hidden">
        <h3 className="text-lg font-semibold text-gray-800 mb-4 flex items-center gap-2">
          <FileOutput size={18} className="text-gov-blue" /> Configure New Report
        </h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 items-end">
          <div className="lg:col-span-2">
            <Select
              label="Report Type"
              options={reportTypes.map(rt => ({ label: rt, value: rt }))}
              value={selectedReportType}
              onChange={(e) => setSelectedReportType(e.target.value)}
            />
          </div>
          
          <Select
            label="Date Range"
            options={dateRangeOptions.map(r => ({ label: r, value: r }))}
            value={dateRange}
            onChange={(e) => setDateRange(e.target.value)}
          />
          
          <Select
            label="District (Optional)"
            options={[{ label: 'All Districts', value: '' }, ...districtsList.map(d => ({ label: d, value: d }))]}
            value={districtFilter}
            onChange={(e) => setDistrictFilter(e.target.value)}
          />
          
          <Select
            label="Village (Optional)"
            options={[{ label: 'All Villages', value: '' }, ...villagesList.map(v => ({ label: v, value: v }))]}
            value={villageFilter}
            onChange={(e) => setVillageFilter(e.target.value)}
          />
          
          <Select
            label="Operator (Optional)"
            options={[{ label: 'All Operators', value: '' }, ...operatorsList.map(o => ({ label: o.name, value: o.name }))]}
            value={operatorFilter}
            onChange={(e) => setOperatorFilter(e.target.value)}
          />
        </div>
        
        <div className="mt-6 flex flex-wrap justify-between items-center border-t border-gray-100 pt-4">
          <button 
            onClick={handleClearFilters}
            className="text-sm text-gray-500 hover:text-gov-blue flex items-center gap-1 font-medium"
          >
            <RefreshCw size={14} /> Reset Configuration
          </button>
          
          <Button 
            onClick={handleGenerateReport} 
            disabled={isGenerating}
            className="flex items-center gap-2"
          >
            {isGenerating ? (
              <><div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div> Generating...</>
            ) : (
              <><FileText size={16} /> Generate Report</>
            )}
          </Button>
        </div>
      </Card>

      {/* Report Preview Section (Printable Area) */}
      {previewData ? (
        <Card className="p-0 overflow-hidden shadow-lg border-gray-300 print:shadow-none print:border-none print:m-0 print:p-0">
          {/* Action Bar (Hidden when printing) */}
          <div className="bg-gray-50 border-b border-gray-200 p-3 flex justify-between items-center print:hidden">
            <div className="flex items-center gap-2 text-green-700">
              <CheckCircle size={18} />
              <span className="text-sm font-semibold">Report Generated Successfully</span>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" size="sm" onClick={handlePrint} className="flex items-center gap-1">
                <Printer size={14} /> Print
              </Button>
              <Button size="sm" onClick={handleDownloadCSV} className="flex items-center gap-1 bg-green-600 hover:bg-green-700 text-white border-green-600 hover:border-green-700">
                <Download size={14} /> Download CSV
              </Button>
            </div>
          </div>

          {/* Printable Report Content */}
          <div className="p-8 bg-white print:p-0">
            {/* Report Header */}
            <div className="text-center border-b-2 border-gray-800 pb-6 mb-6">
              <h1 className="text-3xl font-bold text-gray-900 uppercase tracking-widest mb-2">JALTRACK</h1>
              <h2 className="text-xl font-semibold text-gray-700">{selectedReportType}</h2>
              <p className="text-sm text-gray-500 mt-2">Generated on: {new Date().toLocaleString()}</p>
            </div>
            
            {/* Report Metadata */}
            <div className="grid grid-cols-2 gap-4 mb-8 text-sm">
              <div className="flex gap-2">
                <span className="font-semibold text-gray-700 w-24">Date Range:</span>
                <span className="text-gray-900">{dateRange}</span>
              </div>
              <div className="flex gap-2">
                <span className="font-semibold text-gray-700 w-24">Village Scope:</span>
                <span className="text-gray-900">{villageFilter || 'All Villages'}</span>
              </div>
              <div className="flex gap-2">
                <span className="font-semibold text-gray-700 w-24">District:</span>
                <span className="text-gray-900">{districtFilter || 'All Districts'}</span>
              </div>
              <div className="flex gap-2">
                <span className="font-semibold text-gray-700 w-24">Operator:</span>
                <span className="text-gray-900">{operatorFilter || 'All Operators'}</span>
              </div>
            </div>

            {/* Summary Statistics */}
            <div className="mb-8">
              <h3 className="text-lg font-bold text-gray-800 border-b border-gray-200 pb-2 mb-4">Summary Statistics</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {Object.entries(previewData.summary).map(([key, value], idx) => (
                  <div key={idx} className="bg-gray-50 p-3 rounded border border-gray-100">
                    <p className="text-xs text-gray-500 uppercase tracking-wide mb-1">
                      {key.replace(/([A-Z])/g, ' $1').trim()}
                    </p>
                    <p className="text-lg font-bold text-gray-900">{value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Detailed Table */}
            <div>
              <h3 className="text-lg font-bold text-gray-800 border-b border-gray-200 pb-2 mb-4">Detailed Breakdown</h3>
              <div className="overflow-x-auto border border-gray-200 rounded">
                <table className="w-full text-left border-collapse text-sm">
                  <thead>
                    <tr className="bg-gray-100">
                      {previewData.columns.map((col, idx) => (
                        <th key={idx} className="border-b border-gray-200 p-3 font-semibold text-gray-700">{col}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {previewData.data.map((row, idx) => (
                      <tr key={idx} className="hover:bg-gray-50 border-b border-gray-100 last:border-0">
                        {Object.values(row).map((val, vIdx) => (
                          <td key={vIdx} className="p-3 text-gray-800">{val}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            <div className="mt-12 text-center text-sm text-gray-400 print:block">
              --- End of Report ---
            </div>
          </div>
        </Card>
      ) : (
        <Card className="p-12 flex flex-col items-center justify-center text-center bg-gray-50/50 border-dashed print:hidden">
          <FileText size={48} className="text-gray-300 mb-4" />
          <h3 className="text-lg font-medium text-gray-900">No report generated yet</h3>
          <p className="text-gray-500 text-sm mt-1 max-w-md">Select your preferred report type and filters above, then click 'Generate Report' to view the preview here.</p>
        </Card>
      )}

      {/* Recent Reports History (Hidden when printing) */}
      <Card className="print:hidden">
        <div className="p-4 border-b">
          <h3 className="text-lg font-semibold text-gray-800 flex items-center gap-2">
            <Calendar size={18} className="text-gray-500" /> Recent Reports History
          </h3>
        </div>
        <div className="overflow-x-auto">
          <Table columns={historyColumns} data={history} keyExtractor={row => row.id} />
        </div>
      </Card>
      
    </div>
  );
};

export default Reports;
